services:
  db:
    image: postgres:16-alpine
    container_name: db_loja
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend_loja
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=8000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRE_MINUTES=${JWT_EXPIRE_MINUTES}
    volumes:
      - ./backups:/app/backups
      - ./backend/app:/app/app
      - ./db/init:/app/db/init
    depends_on:
      db:
        condition: service_healthy


  frontend:
    build: ./frontend
    container_name: frontend_loja
    restart: always
    ports:
      - "3000:3000"
    environment:
      - WDS_SOCKET_PORT=0
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    stdin_open: true
    tty: true

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_loja
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

  loja-virtual:
    build: ./loja-virtual
    container_name: loja_virtual_app
    restart: always
    ports:
      - "3001:3000"
    environment:
      - WDS_SOCKET_PORT=0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./loja-virtual/src:/app/src
      - ./loja-virtual/public:/app/public
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  postgres_data:
